# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Jonathan Gan"
subtitle: "See the world through my eyes!"
author: "Jonathan Gan"
header:
 title: "Photography"
 subtitle: "by Jonathan Gab"
footer:
 name: "Hey there, my name is Jonathan"
 bio: "I am a developer and a tech aficionado from Florida. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/ramswaroop"
  instagram: "https://www.instagram.com/jongan69"
  linkedin: "https://in.linkedin.com/jongan69"
  github: "https://www.github.com/jongan69"
